"""Golden-value regression tests against the published implementation.

``tests/data/seizure_segment_1_golden.npz`` holds the outputs of brainmaze-torch
0.1.1 (commit fb21964), generated by ``tests/data/make_golden_reference.py`` from
that commit's code. Wherever the old code evaluated a point (inside the kept part
of one of its windows) and the 1 s segment is valid, the current implementation
must give the same probability; invalid segments must be NaN. Any change in the
numbers of the published method (e.g. an extra window changing values, a time
shift, a different normalisation) fails here.
"""
from pathlib import Path

import numpy as np
import pytest
from scipy.io import loadmat

from brainmaze_torch.seizure_detection import (
    infer_seizure_probability,
    load_trained_model,
    predict_channel_seizure_probability,
    preprocess_input,
)

DATA = Path(__file__).resolve().parent / "data"
# float32 CNN/LSTM inference differs across BLAS kernels and platforms by ~1e-6;
# real changes of the method are orders of magnitude larger (review R1: up to 0.8).
ATOL = 1e-4

GOLD = np.load(DATA / "seizure_segment_1_golden.npz")
CASES = sorted({k[:-len("_defined")] for k in GOLD.files if k.endswith("_defined")})


@pytest.fixture(scope="module")
def fixture_signal():
    dat = loadmat(DATA / "seizure_segment_1.mat")
    return dat["data"].squeeze().astype(np.float64), int(float(dat["fs"].squeeze()))


@pytest.fixture(scope="module")
def model():
    return load_trained_model("modelA")


def _invalid_segments(x, fs, n_out):
    hop = fs // 2
    bad = np.zeros(n_out, dtype=bool)
    bad[0] = True
    blocks = x[:n_out * hop].reshape(n_out, hop)
    blk_bad = ~np.isfinite(blocks).all(axis=1)
    bad[1:] |= blk_bad[:-1] | blk_bad[1:]
    return bad


def test_cases_present():
    assert {"full", "trunc655", "gap500_700", "gap100_260", "emu_trunc655"} <= set(CASES)


@pytest.mark.parametrize("case", CASES)
def test_matches_published_method(case, fixture_signal, model):
    x_full, fs = fixture_signal
    stop_s = float(GOLD[f"{case}_stop_s"])
    gap = GOLD[f"{case}_gap"]
    window_s, step_s, discard_edges_s = GOLD[f"{case}_kw"]
    x = x_full.copy() if np.isnan(stop_s) else x_full[:int(round(stop_s * fs))].copy()
    if np.all(np.isfinite(gap)):
        x[int(gap[0] * fs):int(gap[1] * fs)] = np.nan

    t, p = predict_channel_seizure_probability(
        x, fs, model, window_s=window_s, step_s=step_s, discard_edges_s=discard_edges_s)
    ref, defined = GOLD[f"{case}_prob"], GOLD[f"{case}_defined"]
    n = min(p.size, ref.size)
    invalid = _invalid_segments(x, fs, p.size)

    # NaN exactly at invalid segments (t=0, gaps); a value everywhere else
    np.testing.assert_array_equal(np.isnan(p), invalid)
    cmp = defined[:n] & ~invalid[:n]
    assert cmp.sum() > 900
    np.testing.assert_allclose(p[:n][cmp], ref[:n][cmp], rtol=0, atol=ATOL)
    np.testing.assert_allclose(t, np.arange(p.size) * 0.5)


def test_spectrogram_and_window_inference_match(fixture_signal, model):
    x_full, fs = fixture_signal
    sxx = preprocess_input(x_full[:300 * fs].reshape(1, -1), fs)
    np.testing.assert_allclose(sxx, GOLD["spec_sxx"], rtol=0, atol=1e-4)
    prob = infer_seizure_probability(sxx, model)
    np.testing.assert_allclose(prob, GOLD["spec_prob"], rtol=0, atol=ATOL)
